// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHistory(arg1) {
  return window['go']['main']['App']['AddHistory'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CopyPath(arg1) {
  return window['go']['main']['App']['CopyPath'](arg1);
}

export function CopyToDesktop(arg1) {
  return window['go']['main']['App']['CopyToDesktop'](arg1);
}

export function CutFiles(arg1) {
  return window['go']['main']['App']['CutFiles'](arg1);
}

export function DeleteToRecycleBin(arg1) {
  return window['go']['main']['App']['DeleteToRecycleBin'](arg1);
}

export function GetAboutMessage() {
  return window['go']['main']['App']['GetAboutMessage']();
}

export function GetDrives() {
  return window['go']['main']['App']['GetDrives']();
}

export function GetExclude() {
  return window['go']['main']['App']['GetExclude']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetPreview(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetPreview'](arg1, arg2, arg3);
}

export function GetReleasesURL() {
  return window['go']['main']['App']['GetReleasesURL']();
}

export function GetSavedSearches() {
  return window['go']['main']['App']['GetSavedSearches']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function SetDrives(arg1) {
  return window['go']['main']['App']['SetDrives'](arg1);
}

export function SetExclude(arg1) {
  return window['go']['main']['App']['SetExclude'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function ShowInExplorer(arg1) {
  return window['go']['main']['App']['ShowInExplorer'](arg1);
}

export function StartDrag(arg1) {
  return window['go']['main']['App']['StartDrag'](arg1);
}

export function StartScan(arg1) {
  return window['go']['main']['App']['StartScan'](arg1);
}

export function ToggleSavedSearch(arg1) {
  return window['go']['main']['App']['ToggleSavedSearch'](arg1);
}
