// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddHistory(arg1:string):Promise<Array<string>>;

export function CheckForUpdate():Promise<string>;

export function CopyPath(arg1:string):Promise<string>;

export function CopyToDesktop(arg1:string):Promise<string>;

export function CutFiles(arg1:Array<string>):Promise<string>;

export function DeleteToRecycleBin(arg1:Array<string>):Promise<string>;

export function GetAboutMessage():Promise<Record<string, string>>;

export function GetDrives():Promise<string>;

export function GetExclude():Promise<string>;

export function GetHistory():Promise<Array<string>>;

export function GetLanguage():Promise<string>;

export function GetReleasesURL():Promise<string>;

export function GetSavedSearches():Promise<Array<string>>;

export function GetPreview(arg1:string,arg2:number,arg3:string):Promise<main.PreviewResult>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function Search(arg1:string):Promise<Array<main.fileEntry>>;

export function SetDrives(arg1:string):Promise<string>;

export function SetExclude(arg1:string):Promise<string>;

export function SetLanguage(arg1:string):Promise<void>;

export function RenameFile(arg1:string,arg2:string):Promise<string>;

export function ShowInExplorer(arg1:string):Promise<void>;

export function StartDrag(arg1:Array<string>):Promise<void>;

export function ToggleSavedSearch(arg1:string):Promise<Array<string>>;

export function StartScan(arg1:boolean):Promise<void>;
